namespace FPSOptimizer.Localization
{
    public enum Language { RO, EN }

    public static class StringResources
    {
        private static Language _lang = Language.RO;
        public static Language CurrentLanguage
        {
            get => _lang;
            set => _lang = value;
        }

        public static string Get(string key) => _lang == Language.EN
            ? EN.TryGetValue(key, out var en) ? en : key
            : RO.TryGetValue(key, out var ro) ? ro : key;

        // ── Sidebar / MainWindow ────────────────────────────────────────────────
        public static readonly Dictionary<string, string> RO = new()
        {
            ["App.Title"]            = "Windows FPS Optimizer Pro v1.3.0",
            ["SideBar.Admin"]        = "Administrator",
            ["SideBar.Loading"]      = "Se incarca informatii sistem...",
            ["Btn.Back"]             = "◀   Înapoi",
            ["Btn.Next"]             = "Continuă   ▶",
            ["Btn.Results"]          = "Rezultate   ▶",
            ["Btn.Close"]            = "✓   Închide",
            ["Step.Welcome"]         = "Bun venit",
            ["Step.WelcomeDesc"]     = "Introducere",
            ["Step.Scan"]            = "Scanare",
            ["Step.ScanDesc"]        = "Analiza PC",
            ["Step.Backup"]          = "Protecție",
            ["Step.BackupDesc"]      = "Backup & Restore",
            ["Step.Options"]         = "Configurare",
            ["Step.OptionsDesc"]     = "Alegeri opțiuni",
            ["Step.Execute"]         = "Execuție",
            ["Step.ExecuteDesc"]     = "Optimizare live",
            ["Step.Profiles"]        = "Profil",
            ["Step.ProfilesDesc"]   = "Preset optimizare",
            ["Step.Done"]            = "Finalizat",
            ["Step.DoneDesc"]        = "Gata!",

            // ── PageProfiles ────────────────────────────────────────────────────
            ["Profiles.Title"]       = "Profil de Optimizare",
            ["Profiles.Desc"]        = "Alege un profil care se potriveste nevoilor tale. Poti ajusta individual in pasul urmator.",
            ["Profiles.Safe"]        = "Safe",
            ["Profiles.SafeDesc"]    = "Minim — fara riscuri. Ideal pentru PC-uri de birou.",
            ["Profiles.Balanced"]    = "Balanced",
            ["Profiles.BalancedDesc"]= "Recomandat pentru majoritatea utilizatorilor.",
            ["Profiles.Gaming"]      = "Gaming Hardcore",
            ["Profiles.GamingDesc"]  = "Maxim FPS — toate optimizarile activate.",
            ["Profiles.ModuleCount"] = "{0} module",

            // ── PageWelcome ─────────────────────────────────────────────────────
            ["Welcome.WelcomeTo"]    = "Bun venit la",
            ["Welcome.AppName"]      = "Windows FPS Optimizer Pro",
            ["Welcome.Subtitle"]     = "Optimizare completa in 6 pasi simpli — sigura, cu backup si Restore Point Windows.",
            ["Welcome.Safe"]         = "100% Sigur",
            ["Welcome.SafeDesc"]     = "Restore Point Windows + backup registri inainte de orice modificare.",
            ["Welcome.Perms"]        = "Permisiuni Clare",
            ["Welcome.PermsDesc"]    = "Fiecare optiune are indicator de risc si descriere tehnica detaliata.",
            ["Welcome.FPS"]          = "FPS Maxim",
            ["Welcome.FPSDesc"]      = "GPU Priority 8, Core Parking off, Nagle off, tweaks FPS verificate.",
            ["Welcome.Wizard"]       = "Wizard Pas cu Pas",
            ["Welcome.WizardDesc"]   = "6 pasi cu explicatii clare. Tu decizi exact ce se aplica.",
            ["Welcome.NoBloat"]      = "Fara Bloatware",
            ["Welcome.NoBloatDesc"]  = "40+ aplicatii inutile si 25+ servicii de fundal eliminate.",
            ["Welcome.Restore"]      = "Restaurare Usoara",
            ["Welcome.RestoreDesc"]  = "Script RESTAURARE.ps1 generat automat pe Desktop.",
            ["Welcome.WarnTitle"]    = "⚠️  Citeste inainte de a continua",
            ["Welcome.Warn1"]        = "• Programul ruleaza cu drepturi Administrator (necesar pentru a aplica optimizarile)",
            ["Welcome.Warn2"]        = "• Se creeaza automat Restore Point Windows si backup registri inainte de orice",
            ["Welcome.Warn3"]        = "• NU se modifica BIOS, firmware, voltaje, frecvente CPU/GPU sau drivere critice de placa de baza",
            ["Welcome.Warn4"]        = "• Dupa optimizare, reporneste PC-ul pentru efect complet",
            ["Welcome.Warn5"]        = "• Fiecare optiune este deselectabila individual — tu controlezi tot",

            // ── PageScan ────────────────────────────────────────────────────────
            ["Scan.Title"]           = "Scanare Sistem",
            ["Scan.Desc"]            = "Analiza hardware si sfaturi personalizate pentru placa ta video.",
            ["Scan.Scanning"]        = "Se scaneaza...",
            ["Scan.CPU"]             = "🔲  PROCESOR",
            ["Scan.RAM"]             = "💾  MEMORIE RAM",
            ["Scan.GPU"]             = "🎮  PLACA VIDEO",
            ["Scan.OS"]              = "🪟  SISTEM OPERARE",
            ["Scan.Disk"]            = "💿  STOCARE C:",
            ["Scan.Power"]           = "⚡  PLAN ENERGIE",
            ["Scan.PowerSub"]        = "Optimizer va seta Ultimate Performance",
            ["Scan.Tips"]            = "💡  SFATURI PERSONALIZATE PENTRU PLACA TA VIDEO",
            ["Scan.TipsLoading"]     = "Scanarea se incarca automat...",
            ["Scan.CpuSub"]          = "{0} nuclee / {1} thread-uri",
            ["Scan.DiskFree"]        = "{0:0.#} GB liber / {1:0} GB",
            ["Scan.DiskSsd"]         = "✓ SSD detectat — TRIM va fi activat",
            ["Scan.DiskHdd"]         = "HDD detectat",
            ["Scan.OsBuild"]         = "Build: {0}{1}",
            ["Scan.Win11"]           = "  (Windows 11)",
            ["Scan.Win10"]           = "  (Windows 10)",
            ["Scan.NotDone"]         = "Scanarea nu s-a terminat. Continui fara informatii sistem?",

            // ── PageBackup ──────────────────────────────────────────────────────
            ["Backup.Title"]         = "Protecție Sistem",
            ["Backup.Desc"]          = "Creeaza backup complet inainte de orice modificare. Poti reveni oricand.",
            ["Backup.RestorePoint"]  = "Windows System Restore Point",
            ["Backup.RPBadge"]       = "✓  Recomandat",
            ["Backup.RPDesc"]        = "Creeaza un punct de restaurare nativ Windows. Poti reveni complet din System Restore (Win+S → 'Create a restore point').",
            ["Backup.RPRisk"]        = "Risc: Scazut",
            ["Backup.RPBtn"]         = "Creează Acum",
            ["Backup.RPCreating"]    = "Se creează...",
            ["Backup.RPCreated"]     = "✓ Creat",
            ["Backup.RPFailed"]      = "❌ Eșec",
            ["Backup.RPStatusOk"]    = "✓ Punct de restaurare creat cu succes!",
            ["Backup.RPStatusFail"]  = "❌ Eșec la crearea punctului de restaurare. Asigură-te că ai drepturi Administrator.",
            ["Backup.RPNotChecked"]  = "Opțiunea 'Windows System Restore Point' nu este bifată.",
            ["Backup.RegTitle"]      = "Backup Registri Windows (.REG)",
            ["Backup.RegDesc"]       = "Exporta cheile de registri care vor fi modificate. Fisierele .REG sunt salvate pe Desktop si pot fi importate manual oricand cu dublu-click.",
            ["Backup.SvcTitle"]      = "Backup Lista Servicii Windows (.CSV)",
            ["Backup.SvcDesc"]       = "Salveaza starea curenta a tuturor serviciilor intr-un CSV. Util daca vrei sa re-activezi manual un serviciu mai tarziu.",
            ["Backup.Risk.Low"]      = "Risc: Scazut",
            ["Backup.WarnMsg"]       = "Nicio optiune de backup nu este selectata. Optimizarea va continua fara posibilitate de restaurare automata. Nu recomandam aceasta configuratie.",
            ["Backup.WarnTitle"]     = "⚠️  Atentie:",
            ["Backup.OkTitle"]       = "✓  Backup configurat.",
            ["Backup.OkMsg"]         = "Toate fisierele vor fi salvate pe Desktop inainte ca prima optimizare sa inceapa. Scriptul RESTAURARE.ps1 este generat automat.",

            // ── PageOptions ─────────────────────────────────────────────────────
            ["Options.Title"]        = "Configurare Optimizare",
            ["Options.Desc"]         = "Selecteaza ce sa fie optimizat. Fiecare modul are indicator de risc si descriere tehnica.",
            ["Options.SelectAll"]    = "✓  Selecteaza Toate",
            ["Options.SelectNone"]   = "✗  Deselecteaza Toate",
            ["Options.Count"]        = "{0} / {1} module selectate",
            ["Options.ConfirmTitle"] = "Confirmare Finala",
            ["Options.ConfirmMsg"]   = "Urmatoarele {0} optimizari vor fi aplicate:\n\n{1}\n\nContinui?",
            ["Options.MinOne"]       = "Selecteaza cel putin o optimizare.",
            ["Options.Warning"]      = "Atentie",

            // ── PageExecute ─────────────────────────────────────────────────────
            ["Execute.Title"]        = "Execuție Optimizare",
            ["Execute.Desc"]         = "Nu inchide fereastra in timpul optimizarii.",
            ["Execute.Ready"]        = "Pregatire...",
            ["Execute.Elapsed"]      = "Timp scurs: {0}",
            ["Execute.LogLabel"]     = "LOG LIVE",

            // ── PageDone ────────────────────────────────────────────────────────
            ["Done.Title"]           = "Optimizare Finalizata!",
            ["Done.Subtitle"]        = "PC-ul tau este acum configurat pentru performanta maxima la gaming.",
            ["Done.NextSteps"]       = "📋  CE URMEAZĂ",
            ["Done.Step1Title"]      = "Reporneste PC-ul",
            ["Done.Step1Desc"]       = "OBLIGATORIU pentru a aplica modificarile din registri, servicii si plan de energie. Efectul complet apare dupa restart.",
            ["Done.Step1Badge"]      = "  1  ",
            ["Done.GpuTitle"]        = "🎮  Setari GPU Manuale (Important!)",
            ["Done.GpuNvidia"]       = "NVIDIA:",
            ["Done.GpuNvidiaDesc"]   = " NVIDIA Control Panel → Manage 3D Settings → Power management = Prefer Maximum Performance + Low Latency Mode = Ultra",
            ["Done.GpuAmd"]          = "AMD:",
            ["Done.GpuAmdDesc"]      = " AMD Adrenalin → Gaming → Global Graphics → Radeon Anti-Lag = Enabled",
            ["Done.OverlayTitle"]    = "🔕  Dezactiveaza Overlay-urile",
            ["Done.OverlayDesc"]     = "Discord (Ctrl+Shift+I), Steam (Settings → In-Game), GeForce Experience (Alt+Z → Settings → General), Xbox Game Bar (Win+G → Settings). Fiecare overlay activ reduce FPS cu 2-8%.",
            ["Done.MonitorTitle"]    = "📊  Monitorizare Performanta",
            ["Done.MonitorDesc"]     = "Instaleaza MSI Afterburner + RivaTuner Statistics Server (gratuit) pentru overlay FPS, temperatura GPU/CPU si utilizare in timp real in jocuri.",
            ["Done.RestoreTitle"]    = "🛡️  Restaurare",
            ["Done.RestoreDesc"]     = "Backup-ul si Restore Point-ul sunt pe Desktop. Daca ceva nu functioneaza: Win+S → 'Create a restore point' → System Restore → alege punctul FPSOptimizer.",
            ["Done.MaintTitle"]      = "🌡️  Mentinere Performanta",
            ["Done.Maint1"]          = "• Curata praful din PC la fiecare 6-12 luni (temperatura GPU normala sub sarcina: < 85°C)",
            ["Done.Maint2"]          = "• Pasta termica CPU/GPU: inlocuieste la 4-5 ani pentru -10 to -15°C",
            ["Done.Maint3"]          = "• Verifica temperatura GPU cu MSI Afterburner saptamana urmatoare",
            ["Done.Maint4"]          = "• Actualizeaza driverele GPU periodic (GeForce Experience / AMD Adrenalin)",
            ["Done.RestartBtn"]      = "🔄   Restart PC Acum",
            ["Done.RestartConfirm"]  = "Repornesti Windows acum?\n\nAsigura-te ca ai salvat toate documentele deschise.",
            ["Done.RestartTitle"]    = "Restart PC",
            ["Done.RestartCmd"]      = "FPS Optimizer — Restart pentru aplicare optimizari",
        };

        public static readonly Dictionary<string, string> EN = new()
        {
            ["App.Title"]            = "Windows FPS Optimizer Pro v1.3.0",
            ["SideBar.Admin"]        = "Administrator",
            ["SideBar.Loading"]      = "Loading system information...",
            ["Btn.Back"]             = "◀   Back",
            ["Btn.Next"]             = "Continue   ▶",
            ["Btn.Results"]          = "Results   ▶",
            ["Btn.Close"]            = "✓   Close",
            ["Step.Welcome"]         = "Welcome",
            ["Step.WelcomeDesc"]     = "Introduction",
            ["Step.Scan"]            = "Scan",
            ["Step.ScanDesc"]        = "Analyze PC",
            ["Step.Backup"]          = "Protection",
            ["Step.BackupDesc"]      = "Backup & Restore",
            ["Step.Options"]         = "Configuration",
            ["Step.OptionsDesc"]     = "Choose options",
            ["Step.Execute"]         = "Execution",
            ["Step.ExecuteDesc"]     = "Live optimization",
            ["Step.Profiles"]        = "Profile",
            ["Step.ProfilesDesc"]   = "Optimization preset",
            ["Step.Done"]            = "Complete",
            ["Step.DoneDesc"]        = "Done!",

            // ── PageProfiles ────────────────────────────────────────────────────
            ["Profiles.Title"]       = "Optimization Profile",
            ["Profiles.Desc"]        = "Choose a profile that fits your needs. You can adjust individually in the next step.",
            ["Profiles.Safe"]        = "Safe",
            ["Profiles.SafeDesc"]    = "Minimal — no risks. Ideal for office PCs.",
            ["Profiles.Balanced"]    = "Balanced",
            ["Profiles.BalancedDesc"]= "Recommended for most users.",
            ["Profiles.Gaming"]      = "Gaming Hardcore",
            ["Profiles.GamingDesc"]  = "Maximum FPS — all optimizations enabled.",
            ["Profiles.ModuleCount"] = "{0} modules",

            // ── PageWelcome ─────────────────────────────────────────────────────
            ["Welcome.WelcomeTo"]    = "Welcome to",
            ["Welcome.AppName"]      = "Windows FPS Optimizer Pro",
            ["Welcome.Subtitle"]     = "Complete optimization in 6 simple steps — safe, with backup and Windows Restore Point.",
            ["Welcome.Safe"]         = "100% Safe",
            ["Welcome.SafeDesc"]     = "Windows Restore Point + registry backup before any change.",
            ["Welcome.Perms"]        = "Clear Permissions",
            ["Welcome.PermsDesc"]    = "Each option has a risk indicator and detailed technical description.",
            ["Welcome.FPS"]          = "Maximum FPS",
            ["Welcome.FPSDesc"]      = "GPU Priority 8, Core Parking off, Nagle off, verified FPS tweaks.",
            ["Welcome.Wizard"]       = "Step-by-Step Wizard",
            ["Welcome.WizardDesc"]   = "6 steps with clear explanations. You decide exactly what gets applied.",
            ["Welcome.NoBloat"]      = "No Bloatware",
            ["Welcome.NoBloatDesc"]  = "40+ useless apps and 25+ background services removed.",
            ["Welcome.Restore"]      = "Easy Restore",
            ["Welcome.RestoreDesc"]  = "RESTORE.ps1 script auto-generated on Desktop.",
            ["Welcome.WarnTitle"]    = "⚠️  Read before continuing",
            ["Welcome.Warn1"]        = "• The program runs with Administrator rights (required to apply optimizations)",
            ["Welcome.Warn2"]        = "• Windows Restore Point and registry backup are created automatically before anything",
            ["Welcome.Warn3"]        = "• BIOS, firmware, voltages, CPU/GPU frequencies or critical motherboard drivers are NOT modified",
            ["Welcome.Warn4"]        = "• After optimization, restart your PC for full effect",
            ["Welcome.Warn5"]        = "• Each option can be deselected individually — you control everything",

            // ── PageScan ────────────────────────────────────────────────────────
            ["Scan.Title"]           = "System Scan",
            ["Scan.Desc"]            = "Hardware analysis and personalized tips for your graphics card.",
            ["Scan.Scanning"]        = "Scanning...",
            ["Scan.CPU"]             = "🔲  PROCESSOR",
            ["Scan.RAM"]             = "💾  MEMORY RAM",
            ["Scan.GPU"]             = "🎮  GRAPHICS CARD",
            ["Scan.OS"]              = "🪟  OPERATING SYSTEM",
            ["Scan.Disk"]            = "💿  STORAGE C:",
            ["Scan.Power"]           = "⚡  POWER PLAN",
            ["Scan.PowerSub"]        = "Optimizer will set Ultimate Performance",
            ["Scan.Tips"]            = "💡  PERSONALIZED TIPS FOR YOUR GRAPHICS CARD",
            ["Scan.TipsLoading"]     = "Scan loading automatically...",
            ["Scan.CpuSub"]          = "{0} cores / {1} threads",
            ["Scan.DiskFree"]        = "{0:0.#} GB free / {1:0} GB",
            ["Scan.DiskSsd"]         = "✓ SSD detected — TRIM will be enabled",
            ["Scan.DiskHdd"]         = "HDD detected",
            ["Scan.OsBuild"]         = "Build: {0}{1}",
            ["Scan.Win11"]           = "  (Windows 11)",
            ["Scan.Win10"]           = "  (Windows 10)",
            ["Scan.NotDone"]         = "Scan not complete. Continue without system information?",

            // ── PageBackup ──────────────────────────────────────────────────────
            ["Backup.Title"]         = "System Protection",
            ["Backup.Desc"]          = "Create a full backup before any changes. You can restore anytime.",
            ["Backup.RestorePoint"]  = "Windows System Restore Point",
            ["Backup.RPBadge"]       = "✓  Recommended",
            ["Backup.RPDesc"]        = "Create a native Windows restore point. You can fully revert from System Restore (Win+S → 'Create a restore point').",
            ["Backup.RPRisk"]        = "Risk: Low",
            ["Backup.RPBtn"]         = "Create Now",
            ["Backup.RPCreating"]    = "Creating...",
            ["Backup.RPCreated"]     = "✓ Created",
            ["Backup.RPFailed"]      = "❌ Failed",
            ["Backup.RPStatusOk"]    = "✓ Restore point created successfully!",
            ["Backup.RPStatusFail"]  = "❌ Failed to create restore point. Make sure you have Administrator privileges.",
            ["Backup.RPNotChecked"]  = "The 'Windows System Restore Point' option is not checked.",
            ["Backup.RegTitle"]      = "Windows Registry Backup (.REG)",
            ["Backup.RegDesc"]       = "Export the registry keys that will be modified. .REG files are saved on Desktop and can be imported manually anytime by double-clicking.",
            ["Backup.SvcTitle"]      = "Windows Services Backup (.CSV)",
            ["Backup.SvcDesc"]       = "Save the current state of all services to CSV. Useful if you want to manually re-enable a service later.",
            ["Backup.Risk.Low"]      = "Risk: Low",
            ["Backup.WarnMsg"]       = "No backup option is selected. Optimization will continue without automatic restoration capability. We do not recommend this configuration.",
            ["Backup.WarnTitle"]     = "⚠️  Warning:",
            ["Backup.OkTitle"]       = "✓  Backup configured.",
            ["Backup.OkMsg"]         = "All files will be saved on Desktop before the first optimization starts. The RESTORE.ps1 script is generated automatically.",

            // ── PageOptions ─────────────────────────────────────────────────────
            ["Options.Title"]        = "Optimization Configuration",
            ["Options.Desc"]         = "Choose what to optimize. Each module has a risk indicator and technical description.",
            ["Options.SelectAll"]    = "✓  Select All",
            ["Options.SelectNone"]   = "✗  Deselect All",
            ["Options.Count"]        = "{0} / {1} modules selected",
            ["Options.ConfirmTitle"] = "Final Confirmation",
            ["Options.ConfirmMsg"]   = "The following {0} optimizations will be applied:\n\n{1}\n\nContinue?",
            ["Options.MinOne"]       = "Select at least one optimization.",
            ["Options.Warning"]      = "Warning",

            // ── PageExecute ─────────────────────────────────────────────────────
            ["Execute.Title"]        = "Running Optimization",
            ["Execute.Desc"]         = "Do not close the window during optimization.",
            ["Execute.Ready"]        = "Preparing...",
            ["Execute.Elapsed"]      = "Elapsed: {0}",
            ["Execute.LogLabel"]     = "LIVE LOG",

            // ── PageDone ────────────────────────────────────────────────────────
            ["Done.Title"]           = "Optimization Complete!",
            ["Done.Subtitle"]        = "Your PC is now configured for maximum gaming performance.",
            ["Done.NextSteps"]       = "📋  NEXT STEPS",
            ["Done.Step1Title"]      = "Restart your PC",
            ["Done.Step1Desc"]       = "REQUIRED to apply registry, service and power plan changes. Full effect appears after restart.",
            ["Done.Step1Badge"]      = "  1  ",
            ["Done.GpuTitle"]        = "🎮  Manual GPU Settings (Important!)",
            ["Done.GpuNvidia"]       = "NVIDIA:",
            ["Done.GpuNvidiaDesc"]   = " NVIDIA Control Panel → Manage 3D Settings → Power management = Prefer Maximum Performance + Low Latency Mode = Ultra",
            ["Done.GpuAmd"]          = "AMD:",
            ["Done.GpuAmdDesc"]      = " AMD Adrenalin → Gaming → Global Graphics → Radeon Anti-Lag = Enabled",
            ["Done.OverlayTitle"]    = "🔕  Disable Overlays",
            ["Done.OverlayDesc"]     = "Discord (Ctrl+Shift+I), Steam (Settings → In-Game), GeForce Experience (Alt+Z → Settings → General), Xbox Game Bar (Win+G → Settings). Each active overlay reduces FPS by 2-8%.",
            ["Done.MonitorTitle"]    = "📊  Performance Monitoring",
            ["Done.MonitorDesc"]     = "Install MSI Afterburner + RivaTuner Statistics Server (free) for FPS overlay, GPU/CPU temperature and real-time usage in games.",
            ["Done.RestoreTitle"]    = "🛡️  Restore",
            ["Done.RestoreDesc"]     = "Backup and Restore Point are on Desktop. If something doesn't work: Win+S → 'Create a restore point' → System Restore → choose FPSOptimizer point.",
            ["Done.MaintTitle"]      = "🌡️  Performance Maintenance",
            ["Done.Maint1"]          = "• Clean PC dust every 6-12 months (normal GPU temp under load: < 85°C)",
            ["Done.Maint2"]          = "• CPU/GPU thermal paste: replace every 4-5 years for -10 to -15°C",
            ["Done.Maint3"]          = "• Check GPU temperature with MSI Afterburner next week",
            ["Done.Maint4"]          = "• Update GPU drivers periodically (GeForce Experience / AMD Adrenalin)",
            ["Done.RestartBtn"]      = "🔄   Restart PC Now",
            ["Done.RestartConfirm"]  = "Restart Windows now?\n\nMake sure you have saved all open documents.",
            ["Done.RestartTitle"]    = "Restart PC",
            ["Done.RestartCmd"]      = "FPS Optimizer — Restart to apply optimizations",
        };
    }
}
